package com.example.proj;

import static com.example.proj.GeminiChatManager.SYSTEM_PROMPT;

import android.content.Context;
import android.graphics.Typeface;
import android.os.Bundle;
import android.text.SpannableString;
import android.text.method.ScrollingMovementMethod;
import android.text.style.StyleSpan;
import android.view.View;
import android.view.inputmethod.InputMethodManager;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

import com.google.firebase.auth.FirebaseAuth;

import java.util.ArrayList;

/**
 * Activity representing the AI Chat interface where users can interact with a Gemini-based chatbot.
 * This class handles user input, displays the chat history, and manages communication with the AI.
 */
public class AiChatActivity extends AppCompatActivity {

    /** View to display the conversation history */
    private TextView textViewChat;

    /** Input field for the user to type their messages */
    private EditText eTUserInput;

    /** Manager class that handles the connection and logic for the Gemini AI model */
    private GeminiChatManager chatManager;

    /**
     * Initializes the activity, sets up the UI components, and starts the Gemini chat manager.
     * * @param savedInstanceState If the activity is being re-initialized after previously being
     * shut down, this contains the data it most recently supplied.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_ai_chat);

        textViewChat = findViewById(R.id.textViewChat);
        eTUserInput = findViewById(R.id.eTUserInput);

        // Enables scrolling for the chat history TextView
        textViewChat.setMovementMethod(new ScrollingMovementMethod());

        // Initializes the chat manager with a specific system prompt to guide the AI behavior
        chatManager = GeminiChatManager.getInstance(SYSTEM_PROMPT);
    }

    /**
     * Called when the user clicks the send button.
     * Handles keyboard hiding, validation of input, and updating the UI with the user's message.
     * * @param view The view that was clicked (the send button).
     */
    public void sendUserInput(View view) {
        // Hides the soft keyboard after clicking send
        InputMethodManager imm = (InputMethodManager) this.getSystemService(Context.INPUT_METHOD_SERVICE);
        imm.hideSoftInputFromWindow(view.getWindowToken(), 0);

        String userInput = eTUserInput.getText().toString();

        // Validation: Ensure the user entered text
        if (userInput.isEmpty()) {
            Toast.makeText(this, "Please enter your answer", Toast.LENGTH_LONG).show();
            return;
        } else {
            // Append user message to chat history and clear input field
            textViewChat.append("\n" + "you:" + "\n" + userInput + "\n");
            eTUserInput.setText("");

            // Process the message through the AI manager
            processUserInput(userInput);
        }
    }

    /**
     * Sends the user's input to the Gemini AI model and handles the response.
     * Updates the UI on success or displays a friendly error message on failure.
     * * @param userInput The string containing the user's message to the AI.
     */
    private void processUserInput(String userInput) {
        chatManager.sendChatMessage(userInput, new GeminiCallback () {
            /**
             * Triggered when the AI returns a successful response.
             * @param result The text response generated by the AI.
             */
            @Override
            public void onSuccess(String result) {
                textViewChat.append("\n" + result + "\n");
            }

            /**
             * Triggered when there is a communication error or server overload.
             * @param throwable The error details.
             */
            @Override
            public void onFailure(Throwable throwable) {
                runOnUiThread(() -> {
                    textViewChat.append("\n"+"joe:"+"Sorry , the server is in high demand ." +
                            "come back in a minute"+"\n");
                });
            }
        });
    }
}